python getEvent.py 01 ../bs/segPairFile01 ../bs/eventFile01 > ../outputstr/getevent.log
python getEvent.py 02 ../bs/segPairFile02 ../bs/eventFile02 > ../outputstr/getevent.log
python getEvent.py 03 ../bs/segPairFile03 ../bs/eventFile03 > ../outputstr/getevent.log
python getEvent.py 04 ../bs/segPairFile04 ../bs/eventFile04 > ../outputstr/getevent.log
python getEvent.py 05 ../bs/segPairFile05 ../bs/eventFile05 > ../outputstr/getevent.log
python getEvent.py 06 ../bs/segPairFile06 ../bs/eventFile06 > ../outputstr/getevent.log
python getEvent.py 07 ../bs/segPairFile07 ../bs/eventFile07 > ../outputstr/getevent.log
python getEvent.py 08 ../bs/segPairFile08 ../bs/eventFile08 > ../outputstr/getevent.log
python getEvent.py 09 ../bs/segPairFile09 ../bs/eventFile09 > ../outputstr/getevent.log
python getEvent.py 10 ../bs/segPairFile10 ../bs/eventFile10 > ../outputstr/getevent.log
python getEvent.py 11 ../bs/segPairFile11 ../bs/eventFile11 > ../outputstr/getevent.log
python getEvent.py 12 ../bs/segPairFile12 ../bs/eventFile12 > ../outputstr/getevent.log
python getEvent.py 13 ../bs/segPairFile13 ../bs/eventFile13 > ../outputstr/getevent.log
python getEvent.py 14 ../bs/segPairFile14 ../bs/eventFile14 > ../outputstr/getevent.log
python getEvent.py 15 ../bs/segPairFile15 ../bs/eventFile15 > ../outputstr/getevent.log
