python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_01_prob > ~/fred_stock_expData/logs/out.ngram.recheck01
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_02_prob > ~/fred_stock_expData/logs/out.ngram.recheck02
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_03_prob > ~/fred_stock_expData/logs/out.ngram.recheck03
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_04_prob > ~/fred_stock_expData/logs/out.ngram.recheck04
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_05_prob > ~/fred_stock_expData/logs/out.ngram.recheck05
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_06_prob > ~/fred_stock_expData/logs/out.ngram.recheck06
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_07_prob > ~/fred_stock_expData/logs/out.ngram.recheck07
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_08_prob > ~/fred_stock_expData/logs/out.ngram.recheck08
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_09_prob > ~/fred_stock_expData/logs/out.ngram.recheck09
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_10_prob > ~/fred_stock_expData/logs/out.ngram.recheck10
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_11_prob > ~/fred_stock_expData/logs/out.ngram.recheck11
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_12_prob > ~/fred_stock_expData/logs/out.ngram.recheck12
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_13_prob > ~/fred_stock_expData/logs/out.ngram.recheck13
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_14_prob > ~/fred_stock_expData/logs/out.ngram.recheck14
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_15_prob > ~/fred_stock_expData/logs/out.ngram.recheck15
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_16_prob > ~/fred_stock_expData/logs/out.ngram.recheck16
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_17_prob > ~/fred_stock_expData/logs/out.ngram.recheck17
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_18_prob > ~/fred_stock_expData/logs/out.ngram.recheck18
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_19_prob > ~/fred_stock_expData/logs/out.ngram.recheck19
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_20_prob > ~/fred_stock_expData/logs/out.ngram.recheck20
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_21_prob > ~/fred_stock_expData/logs/out.ngram.recheck21
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_22_prob > ~/fred_stock_expData/logs/out.ngram.recheck22
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_23_prob > ~/fred_stock_expData/logs/out.ngram.recheck23
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_24_prob > ~/fred_stock_expData/logs/out.ngram.recheck24
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_25_prob > ~/fred_stock_expData/logs/out.ngram.recheck25
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_26_prob > ~/fred_stock_expData/logs/out.ngram.recheck26
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_27_prob > ~/fred_stock_expData/logs/out.ngram.recheck27
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_28_prob > ~/fred_stock_expData/logs/out.ngram.recheck28
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_29_prob > ~/fred_stock_expData/logs/out.ngram.recheck29
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_30_prob > ~/fred_stock_expData/logs/out.ngram.recheck30
python ngramProb_recheck.py ~/corpus/data_stock201504/segment/grams_qtwe/qngrams_31_prob > ~/fred_stock_expData/logs/out.ngram.recheck31
#exit
