python getbtySkl.py 01 > ~/fred_stock_expData/logs/out.btyskl01.word
python getbtySkl.py 02 > ~/fred_stock_expData/logs/out.btyskl02.word
python getbtySkl.py 03 > ~/fred_stock_expData/logs/out.btyskl03.word
python getbtySkl.py 04 > ~/fred_stock_expData/logs/out.btyskl04.word
python getbtySkl.py 05 > ~/fred_stock_expData/logs/out.btyskl05.word
python getbtySkl.py 06 > ~/fred_stock_expData/logs/out.btyskl06.word
python getbtySkl.py 07 > ~/fred_stock_expData/logs/out.btyskl07.word
python getbtySkl.py 08 > ~/fred_stock_expData/logs/out.btyskl08.word
python getbtySkl.py 09 > ~/fred_stock_expData/logs/out.btyskl09.word
python getbtySkl.py 10 > ~/fred_stock_expData/logs/out.btyskl10.word
python getbtySkl.py 11 > ~/fred_stock_expData/logs/out.btyskl11.word
python getbtySkl.py 12 > ~/fred_stock_expData/logs/out.btyskl12.word
python getbtySkl.py 13 > ~/fred_stock_expData/logs/out.btyskl13.word
python getbtySkl.py 14 > ~/fred_stock_expData/logs/out.btyskl14.word
python getbtySkl.py 15 > ~/fred_stock_expData/logs/out.btyskl15.word
python getbtySkl.py 16 > ~/fred_stock_expData/logs/out.btyskl16.word
python getbtySkl.py 17 > ~/fred_stock_expData/logs/out.btyskl17.word
python getbtySkl.py 18 > ~/fred_stock_expData/logs/out.btyskl18.word
python getbtySkl.py 19 > ~/fred_stock_expData/logs/out.btyskl19.word
python getbtySkl.py 20 > ~/fred_stock_expData/logs/out.btyskl20.word
python getbtySkl.py 21 > ~/fred_stock_expData/logs/out.btyskl21.word
python getbtySkl.py 22 > ~/fred_stock_expData/logs/out.btyskl22.word
python getbtySkl.py 23 > ~/fred_stock_expData/logs/out.btyskl23.word
python getbtySkl.py 24 > ~/fred_stock_expData/logs/out.btyskl24.word
python getbtySkl.py 25 > ~/fred_stock_expData/logs/out.btyskl25.word
python getbtySkl.py 26 > ~/fred_stock_expData/logs/out.btyskl26.word
python getbtySkl.py 27 > ~/fred_stock_expData/logs/out.btyskl27.word
python getbtySkl.py 28 > ~/fred_stock_expData/logs/out.btyskl28.word
python getbtySkl.py 29 > ~/fred_stock_expData/logs/out.btyskl29.word
python getbtySkl.py 30 > ~/fred_stock_expData/logs/out.btyskl30.word
python getbtySkl.py 31 > ~/fred_stock_expData/logs/out.btyskl31.word
#exit
