python getEvent.py 01 > ~/fred_stock_expData/logs/out.event01
python getEvent.py 02 > ~/fred_stock_expData/logs/out.event02
python getEvent.py 03 > ~/fred_stock_expData/logs/out.event03
python getEvent.py 04 > ~/fred_stock_expData/logs/out.event04
python getEvent.py 05 > ~/fred_stock_expData/logs/out.event05
python getEvent.py 06 > ~/fred_stock_expData/logs/out.event06
python getEvent.py 07 > ~/fred_stock_expData/logs/out.event07
python getEvent.py 08 > ~/fred_stock_expData/logs/out.event08
python getEvent.py 09 > ~/fred_stock_expData/logs/out.event09
python getEvent.py 10 > ~/fred_stock_expData/logs/out.event10
python getEvent.py 11 > ~/fred_stock_expData/logs/out.event11
python getEvent.py 12 > ~/fred_stock_expData/logs/out.event12
python getEvent.py 13 > ~/fred_stock_expData/logs/out.event13
python getEvent.py 14 > ~/fred_stock_expData/logs/out.event14
python getEvent.py 15 > ~/fred_stock_expData/logs/out.event15
python getEvent.py 16 > ~/fred_stock_expData/logs/out.event16
python getEvent.py 17 > ~/fred_stock_expData/logs/out.event17
python getEvent.py 18 > ~/fred_stock_expData/logs/out.event18
python getEvent.py 19 > ~/fred_stock_expData/logs/out.event19
python getEvent.py 20 > ~/fred_stock_expData/logs/out.event20
python getEvent.py 21 > ~/fred_stock_expData/logs/out.event21
python getEvent.py 22 > ~/fred_stock_expData/logs/out.event22
python getEvent.py 23 > ~/fred_stock_expData/logs/out.event23
python getEvent.py 24 > ~/fred_stock_expData/logs/out.event24
python getEvent.py 25 > ~/fred_stock_expData/logs/out.event25
python getEvent.py 26 > ~/fred_stock_expData/logs/out.event26
python getEvent.py 27 > ~/fred_stock_expData/logs/out.event27
python getEvent.py 28 > ~/fred_stock_expData/logs/out.event28
python getEvent.py 29 > ~/fred_stock_expData/logs/out.event29
python getEvent.py 30 > ~/fred_stock_expData/logs/out.event30
python getEvent.py 31 > ~/fred_stock_expData/logs/out.event31
#exit
