python getbtySkl.py 01 > ~/fbes_expData/logs/out.btyskl01
python getbtySkl.py 02 > ~/fbes_expData/logs/out.btyskl02
python getbtySkl.py 03 > ~/fbes_expData/logs/out.btyskl03
python getbtySkl.py 04 > ~/fbes_expData/logs/out.btyskl04
python getbtySkl.py 05 > ~/fbes_expData/logs/out.btyskl05
python getbtySkl.py 06 > ~/fbes_expData/logs/out.btyskl06
python getbtySkl.py 07 > ~/fbes_expData/logs/out.btyskl07
python getbtySkl.py 08 > ~/fbes_expData/logs/out.btyskl08
python getbtySkl.py 09 > ~/fbes_expData/logs/out.btyskl09
python getbtySkl.py 10 > ~/fbes_expData/logs/out.btyskl10
python getbtySkl.py 11 > ~/fbes_expData/logs/out.btyskl11
python getbtySkl.py 12 > ~/fbes_expData/logs/out.btyskl12
python getbtySkl.py 13 > ~/fbes_expData/logs/out.btyskl13
python getbtySkl.py 14 > ~/fbes_expData/logs/out.btyskl14
python getbtySkl.py 15 > ~/fbes_expData/logs/out.btyskl15
#sync
python getEventSegPair.py 01 > ~/fbes_expData/logs/out.sklpair01
python getEventSegPair.py 02 > ~/fbes_expData/logs/out.sklpair02
python getEventSegPair.py 03 > ~/fbes_expData/logs/out.sklpair03
python getEventSegPair.py 04 > ~/fbes_expData/logs/out.sklpair04
python getEventSegPair.py 05 > ~/fbes_expData/logs/out.sklpair05
python getEventSegPair.py 06 > ~/fbes_expData/logs/out.sklpair06
python getEventSegPair.py 07 > ~/fbes_expData/logs/out.sklpair07
python getEventSegPair.py 08 > ~/fbes_expData/logs/out.sklpair08
python getEventSegPair.py 09 > ~/fbes_expData/logs/out.sklpair09
python getEventSegPair.py 10 > ~/fbes_expData/logs/out.sklpair10
python getEventSegPair.py 11 > ~/fbes_expData/logs/out.sklpair11
python getEventSegPair.py 12 > ~/fbes_expData/logs/out.sklpair12
python getEventSegPair.py 13 > ~/fbes_expData/logs/out.sklpair13
python getEventSegPair.py 14 > ~/fbes_expData/logs/out.sklpair14
python getEventSegPair.py 15 > ~/fbes_expData/logs/out.sklpair15
#sync
python getEvent.py 01 > ~/fbes_expData/logs/out.event01
python getEvent.py 02 > ~/fbes_expData/logs/out.event02
python getEvent.py 03 > ~/fbes_expData/logs/out.event03
python getEvent.py 04 > ~/fbes_expData/logs/out.event04
python getEvent.py 05 > ~/fbes_expData/logs/out.event05
python getEvent.py 06 > ~/fbes_expData/logs/out.event06
python getEvent.py 07 > ~/fbes_expData/logs/out.event07
python getEvent.py 08 > ~/fbes_expData/logs/out.event08
python getEvent.py 09 > ~/fbes_expData/logs/out.event09
python getEvent.py 10 > ~/fbes_expData/logs/out.event10
python getEvent.py 11 > ~/fbes_expData/logs/out.event11
python getEvent.py 12 > ~/fbes_expData/logs/out.event12
python getEvent.py 13 > ~/fbes_expData/logs/out.event13
python getEvent.py 14 > ~/fbes_expData/logs/out.event14
python getEvent.py 15 > ~/fbes_expData/logs/out.event15
#exit
