python getEvent.py 01 > ~/fred_stock_expData/logs/out.event01.segment
python getEvent.py 02 > ~/fred_stock_expData/logs/out.event02.segment
python getEvent.py 03 > ~/fred_stock_expData/logs/out.event03.segment
python getEvent.py 04 > ~/fred_stock_expData/logs/out.event04.segment
python getEvent.py 05 > ~/fred_stock_expData/logs/out.event05.segment
python getEvent.py 06 > ~/fred_stock_expData/logs/out.event06.segment
python getEvent.py 07 > ~/fred_stock_expData/logs/out.event07.segment
python getEvent.py 08 > ~/fred_stock_expData/logs/out.event08.segment
python getEvent.py 09 > ~/fred_stock_expData/logs/out.event09.segment
python getEvent.py 10 > ~/fred_stock_expData/logs/out.event10.segment
python getEvent.py 11 > ~/fred_stock_expData/logs/out.event11.segment
python getEvent.py 12 > ~/fred_stock_expData/logs/out.event12.segment
python getEvent.py 13 > ~/fred_stock_expData/logs/out.event13.segment
python getEvent.py 14 > ~/fred_stock_expData/logs/out.event14.segment
python getEvent.py 15 > ~/fred_stock_expData/logs/out.event15.segment
python getEvent.py 16 > ~/fred_stock_expData/logs/out.event16.segment
python getEvent.py 17 > ~/fred_stock_expData/logs/out.event17.segment
python getEvent.py 18 > ~/fred_stock_expData/logs/out.event18.segment
python getEvent.py 19 > ~/fred_stock_expData/logs/out.event19.segment
python getEvent.py 20 > ~/fred_stock_expData/logs/out.event20.segment
python getEvent.py 21 > ~/fred_stock_expData/logs/out.event21.segment
python getEvent.py 22 > ~/fred_stock_expData/logs/out.event22.segment
python getEvent.py 23 > ~/fred_stock_expData/logs/out.event23.segment
python getEvent.py 24 > ~/fred_stock_expData/logs/out.event24.segment
python getEvent.py 25 > ~/fred_stock_expData/logs/out.event25.segment
python getEvent.py 26 > ~/fred_stock_expData/logs/out.event26.segment
python getEvent.py 27 > ~/fred_stock_expData/logs/out.event27.segment
python getEvent.py 28 > ~/fred_stock_expData/logs/out.event28.segment
python getEvent.py 29 > ~/fred_stock_expData/logs/out.event29.segment
python getEvent.py 30 > ~/fred_stock_expData/logs/out.event30.segment
python getEvent.py 31 > ~/fred_stock_expData/logs/out.event31.segment
#exit
