python getEventSegPair.py 01 > ~/fred_stock_expData/logs/out.sklpair01
python getEventSegPair.py 02 > ~/fred_stock_expData/logs/out.sklpair02
python getEventSegPair.py 03 > ~/fred_stock_expData/logs/out.sklpair03
python getEventSegPair.py 04 > ~/fred_stock_expData/logs/out.sklpair04
python getEventSegPair.py 05 > ~/fred_stock_expData/logs/out.sklpair05
python getEventSegPair.py 06 > ~/fred_stock_expData/logs/out.sklpair06
python getEventSegPair.py 07 > ~/fred_stock_expData/logs/out.sklpair07
python getEventSegPair.py 08 > ~/fred_stock_expData/logs/out.sklpair08
python getEventSegPair.py 09 > ~/fred_stock_expData/logs/out.sklpair09
python getEventSegPair.py 10 > ~/fred_stock_expData/logs/out.sklpair10
python getEventSegPair.py 11 > ~/fred_stock_expData/logs/out.sklpair11
python getEventSegPair.py 12 > ~/fred_stock_expData/logs/out.sklpair12
python getEventSegPair.py 13 > ~/fred_stock_expData/logs/out.sklpair13
python getEventSegPair.py 14 > ~/fred_stock_expData/logs/out.sklpair14
python getEventSegPair.py 15 > ~/fred_stock_expData/logs/out.sklpair15
python getEventSegPair.py 16 > ~/fred_stock_expData/logs/out.sklpair16
python getEventSegPair.py 17 > ~/fred_stock_expData/logs/out.sklpair17
python getEventSegPair.py 18 > ~/fred_stock_expData/logs/out.sklpair18
python getEventSegPair.py 19 > ~/fred_stock_expData/logs/out.sklpair19
python getEventSegPair.py 20 > ~/fred_stock_expData/logs/out.sklpair20
python getEventSegPair.py 21 > ~/fred_stock_expData/logs/out.sklpair21
python getEventSegPair.py 22 > ~/fred_stock_expData/logs/out.sklpair22
python getEventSegPair.py 23 > ~/fred_stock_expData/logs/out.sklpair23
python getEventSegPair.py 24 > ~/fred_stock_expData/logs/out.sklpair24
python getEventSegPair.py 25 > ~/fred_stock_expData/logs/out.sklpair25
python getEventSegPair.py 26 > ~/fred_stock_expData/logs/out.sklpair26
python getEventSegPair.py 27 > ~/fred_stock_expData/logs/out.sklpair27
python getEventSegPair.py 28 > ~/fred_stock_expData/logs/out.sklpair28
python getEventSegPair.py 29 > ~/fred_stock_expData/logs/out.sklpair29
python getEventSegPair.py 30 > ~/fred_stock_expData/logs/out.sklpair30
python getEventSegPair.py 31 > ~/fred_stock_expData/logs/out.sklpair31
#exit
