python getSocialInfo.py 01 > ~/fred_stock_expData/logs/out.socialFea01 &
python getSocialInfo.py 02 > ~/fred_stock_expData/logs/out.socialFea02 &
python getSocialInfo.py 03 > ~/fred_stock_expData/logs/out.socialFea03 &
python getSocialInfo.py 04 > ~/fred_stock_expData/logs/out.socialFea04 &
python getSocialInfo.py 05 > ~/fred_stock_expData/logs/out.socialFea05 &
python getSocialInfo.py 06 > ~/fred_stock_expData/logs/out.socialFea06 &
python getSocialInfo.py 07 > ~/fred_stock_expData/logs/out.socialFea07 &
python getSocialInfo.py 08 > ~/fred_stock_expData/logs/out.socialFea08 &
python getSocialInfo.py 09 > ~/fred_stock_expData/logs/out.socialFea09 &
python getSocialInfo.py 10 > ~/fred_stock_expData/logs/out.socialFea10 &
python getSocialInfo.py 11 > ~/fred_stock_expData/logs/out.socialFea11 &
python getSocialInfo.py 12 > ~/fred_stock_expData/logs/out.socialFea12 &
python getSocialInfo.py 13 > ~/fred_stock_expData/logs/out.socialFea13 &
python getSocialInfo.py 14 > ~/fred_stock_expData/logs/out.socialFea14 &
python getSocialInfo.py 15 > ~/fred_stock_expData/logs/out.socialFea15 &
python getSocialInfo.py 16 > ~/fred_stock_expData/logs/out.socialFea16 &
python getSocialInfo.py 17 > ~/fred_stock_expData/logs/out.socialFea17 &
python getSocialInfo.py 18 > ~/fred_stock_expData/logs/out.socialFea18 &
python getSocialInfo.py 19 > ~/fred_stock_expData/logs/out.socialFea19 &
python getSocialInfo.py 20 > ~/fred_stock_expData/logs/out.socialFea20 &
python getSocialInfo.py 21 > ~/fred_stock_expData/logs/out.socialFea21 &
python getSocialInfo.py 22 > ~/fred_stock_expData/logs/out.socialFea22 &
python getSocialInfo.py 23 > ~/fred_stock_expData/logs/out.socialFea23 &
python getSocialInfo.py 24 > ~/fred_stock_expData/logs/out.socialFea24 &
python getSocialInfo.py 25 > ~/fred_stock_expData/logs/out.socialFea25 &
python getSocialInfo.py 26 > ~/fred_stock_expData/logs/out.socialFea26 &
python getSocialInfo.py 27 > ~/fred_stock_expData/logs/out.socialFea27 &
python getSocialInfo.py 28 > ~/fred_stock_expData/logs/out.socialFea28 &
python getSocialInfo.py 29 > ~/fred_stock_expData/logs/out.socialFea29 &
python getSocialInfo.py 30 > ~/fred_stock_expData/logs/out.socialFea30 &
python getSocialInfo.py 31 > ~/fred_stock_expData/logs/out.socialFea31 &
